apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.repo }}-{{ .Values.branch }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
  selector:
    app: {{ .Release.Name }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
